services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
      - 853:853/tcp
      - 853:853/udp
    volumes:
      - /homelab/adguard-home:/opt/adguardhome/work
      - /homelab/adguard-home/config:/opt/adguardhome/conf
      - /homelab/npmplus/data/tls/certbot/archive/npm-1:/etc/letsencrypt
    networks:
      - srv
    restart: always
networks:
  srv:
    external: true
