services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=${LIBRE_SPEED_PASSWORD}
      - IPINFO_APIKEY=${LIBRE_SPEED_ACCESS_TOKEN}
    volumes:
      - /homelab/librespeed/config:/config
    ports:
      - 3334:80
    restart: unless-stopped
    networks:
      - srv

networks:
  srv:
    external: true
