include:
  - "cloud/immich/docker-compose.immich.yml"
  - "cloud/mealie/docker-compose.mealie.yml"
  - "cloud/nextcloud/docker-compose.nextcloud.yml"
  - "cloud/vaultwarden/docker-compose.vaultwarden.yml"
  - "downloaders/qbittorent/docker-compose.qbittorent.yml"
  - "homelab/diun/docker-compose.diun.yml"
  - "homelab/dockge/docker-compose.dockge.yml"
  - "homelab/homarr/docker-compose.homarr.yml"
  - "homelab/portainer/docker-compose.portainer.yml"
  - "homelab/uptime-kuma/docker-compose.uptime-kuma.yml"
  - "homelab/watchtower/docker-compose.watchtower.yml"
  - "media/jellyfin/docker-compose.jellyfin.yml"
  - "media/overseerr/docker-compose.overseer.yml"
  - "media/plex/docker-compose.plex.yml"
  - "network/adguard-home/docker-compose.adguard-home.yml"
  - "network/npmplus/docker-compose.npmplus.yml"
  - "tools/code-server/docker-compose.code-server.yml"
  - "tools/convertx/docker-compose.convertx.yml"
  - "tools/drawio/docker-compose.drawio.yml"
  - "tools/excalidraw/docker-compose.excalidraw.yml"
  - "tools/it-tools/docker-compose.it-tools.yml"
  - "tools/librespeed/docker-compose.librespeed.yml"
  - "tools/pairdrop/docker-compose.pairdrop.yml"
  - "tools/stirling-pdf/docker-compose.stirling-pdf.yml"
  - "tools/your-spotify/docker-compose.your-spotify.yml"
