include:
  - "homelab/portainer/docker-compose.portainer.yml"
  - "homelab/uptime-kuma/docker-compose.uptime-kuma.yml"
  - "homelab/watchtower/docker-compose.watchtower.yml"
  - "network/npmplus/docker-compose.npmplus.yml"
