services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_IMAGE_VERSION:-latest}
    container_name: uptime-kuma
    volumes:
      - /homelab/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: always
