services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /homelab/uptime-kuma/data:/app/data
    networks:
      - srv
    restart: unless-stopped
    user: 2211:2001

networks:
  srv:
    external: true
