version: "3.8"

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:${DUCKDNS_IMAGE_VERSION:-latest}
    container_name: duckdns
    restart: unless-stopped
    environment:
      - TZ=${TIMEZONE}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ./conf/config:/config
