services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:${DRAWIO_VERSION}
    ports:
      # - ${PORT_DRAWIO_HTTP}:8080
      - ${PORT_DRAWIO_HTTPS}:8443

    networks:
      - srv
    restart: unless-stopped
networks:
  srv:
    external: true
