services:
  npmplus:
    image: zoeyvid/npmplus:${NPMPLUS_IMAGE_VERSION:-latest}
    container_name: npmplus
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - "/homelab/npmplus/data:/data"
      - "/homelab/npmplus/letsencrypt:/etc/letsencrypt"
    environment:
      - TZ=${TIMEZONE}
