services:
  radarr:
    image: linuxserver/radarr:latest
    environment:
      - PUID=1002
      - PGID=2001
      - TZ=Europe/Paris
    ports:
      - 7878:7878
    volumes:
      - /homelab/servarr/radarr/config:/config
      - /data/downloads:/downloads
      - /data/media/movies:/movies
      - /mnt/diskaladoree:/mnt/diskaladoree
      - /home/yann/script/qbit-relocate.sh:/opt/scripts/qbit-relocate.sh:ro
      - /var/log/qbit-relocate.log:/var/log/qbit-relocate.log:rw
    restart: unless-stopped
    networks:
      - srv
  sonarr:
    image: linuxserver/sonarr:latest
    ports:
      - 7979:8989
    environment:
      - PUID=1002
      - PGID=2001
      - TZ=Europe/Paris
    volumes:
      - /homelab/servarr/sonarr/config:/config
      - /data/downloads:/downloads
      - /data/media/series:/series
      - /data/media/animes:/animes
      - /mnt/diskaladoree:/mnt/diskaladoree
      - /home/yann/script/qbit-relocate.sh:/opt/scripts/qbit-relocate.sh:ro
      - /var/log/qbit-relocate.log:/var/log/qbit-relocate.log:rw
    restart: unless-stopped
    networks:
      - srv
  prowlarr:
    image: linuxserver/prowlarr:latest
    environment:
      - PUID=1002
      - PGID=2001
      - TZ=Europe/Paris
    volumes:
      - /homelab/servarr/prowlarr:/config
    ports:
      - 7980:9696
    restart: unless-stopped
    networks:
      - srv
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 7981:8191
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - srv
  autobrr:
    restart: always
    image: ghcr.io/autobrr/autobrr:latest
    user: 1002:2001
    ports:
      - 7474:7474
    volumes:
      - /homelab/servarr/autobrr:/config
    environment:
      - PUID=1002
      - PGID=2001
      - TZ=Europe/Paris
    networks:
      - srv
networks:
  srv:
    external: true
