services:
  pairdrop:
    container_name: pairdrop
    image: linuxserver/pairdrop:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - RATE_LIMIT=${RATE_LIMIT}
      - WS_FALLBACK=false
    ports:
      - ${PORT_PAIRDROP_WEB}:3000
    networks:
      - srv
    restart: unless-stopped

networks:
  srv:
    external: true
