services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    environment:
      - DOMAIN=https://vw.${DOMAIN}
    ports:
      - ${PORT_VAULTWARDEN_WEB}:80
    volumes:
      - /homelab/vaultwarden/data:/data/
    networks:
      - srv
    restart: unless-stopped

networks:
  srv:
    external: true
