services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VAULTWARDEN_VERSION}
    environment:
      - DOMAIN=https://vw.${DOMAIN}
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - INVITATION_ALLOWED=false
    ports:
      - ${PORT_VAULTWARDEN_WEB}:80
    volumes:
      - /homelab/vaultwarden/data:/data/
    networks:
      - srv
    restart: unless-stopped
    user: 2005:2001

networks:
  srv:
    external: true
