services:
  it-tools:
    container_name: it-tools
    image: sharevb/it-tools:latest
    ports:
      - 4005:8080
    networks:
      - srv
    restart: unless-stopped
    user: 2505:2001

networks:
  srv:
    external: true
