services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - 5200:80
    networks:
      - srv
    restart: unless-stopped
    user: 2504:2001

networks:
  srv:
    external: true
