services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    environment:
      - PUID=2301
      - PGID=2001
      - TZ=${TIMEZONE}
      - WEBUI_PORT=${PORT_QBITTORRENT_WEB}
      - TORRENTING_PORT=${PORT_QBITTORRENT_TORRENTING}
    ports:
      - ${PORT_QBITTORRENT_WEB}:${PORT_QBITTORRENT_WEB}
      - ${PORT_QBITTORRENT_TORRENTING}:6881/tcp
      - ${PORT_QBITTORRENT_TORRENTING}:6881/udp
    volumes:
      - /homelab/servarr/qbitorrent/config:/config
      - /data/downloads:/downloads
    networks:
      - srv
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G


networks:
  srv:
    external: true
