services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - VERSION=docker
    volumes:
      - /homelab/plex/config:/config
      - /homelab/plex/tvseries:/tv
      - /homealb/plex/movies:/movies
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
