services:
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    volumes:
      - /homelab/immich/data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT_IMMICH_WEB}:2283
    depends_on:
      - redis
      - database
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      disable: false


  immich_machine_learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - model-cache:/cache
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      disable: false


  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1


  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
      # - DB_STORAGE_TYPE=HDD
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - srv
    restart: unless-stopped


volumes:
  model-cache:

networks:
  srv:
    external: true
