services:
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    volumes:
      - /homelab/immich/data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PORT_IMMICH_WEB}:2283"
    depends_on:
      - redis
      - database
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      disable: false
    user: 2001:2001

  immich_machine_learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - model-cache:/cache
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      disable: false
    user: 2001:2001

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    networks:
      - srv
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    user: 2001:2001

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
      # - DB_STORAGE_TYPE=HDD
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - srv
    restart: unless-stopped
    user: 2001:2001

volumes:
  model-cache:

networks:
  srv:
    external: true
