services:
  npmplus:
    image: zoeyvid/npmplus:${NPMPLUS_IMAGE_VERSION:-latest}
    container_name: npmplus
    restart: always
    ports:
      - "40080:80"
      - "40443:443"
      - "40081:81"
    volumes:
      - "/opt/npmplus:/data"
    environment:
      - TZ=${TIMEZONE}
      - ACME_EMAIL=${NPMPLUS_EMAIL}
