services:
  portainer:
    container_name: portainer
    image: portainer/portainer-${PORTAINER_EDITION:-ce}:${PORTAINER_IMAGE_VERSION:-latest}
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homelab/portainer/data:/data
    restart: always
