services:
  portainer:
    container_name: portainer
    image: portainer/portainer-${PORTAINER_EDITION}:${PORTAINER_VERSION}
    ports:
      - ${PORT_PORTAINER_WEB}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homelab/portainer/data:/data
    networks:
      - srv
    restart: unless-stopped
    user: 2210:2001

networks:
  srv:
    external: true
