services:
  dockge:
    container_name: dockge
    image: louislam/dockge:${DOCKGE_VERSION}
    environment:
      - DOCKGE_STACKS_DIR=/homelab/dockge/stacks
      - DOCKGE_ENABLE_CONSOLE=true
    ports:
      - ${PORT_DOCKGE_WEB}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homelab/dockge/data:/app/data
      - /homelab/dockge/stacks:/homelab/dockge/stacks
    networks:
      - srv
    restart: unless-stopped

networks:
  srv:
    external: true
