services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:${PORTAINER_IMAGE_VERSION:lts}
    ports:
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
