services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:${WATCHTOWER_VERSION}
    environment:
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT}
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - srv
    restart: unless-stopped

networks:
  srv:
    external: true
