services:
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_IMAGE_VERSION:-latest}
    environment:
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-true}
      WATCHTOWER_ROLLING_RESTART: ${WATCHTOWER_ROLLING_RESTART:-true}
      WATCHTOWER_SCHEDULE: ${WATCHTOWER_SCHEDULE:-"0 0 * * *"}
      WATCHTOWER_TIMEOUT: ${WATCHTOWER_TIMEOUT:-60s}
      TZ: ${TZ:-Europe/Paris}
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
