name: Docker Compose Update & Env Vars Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for scripts
        run: |
          chmod +x .github/scripts/check-env-vars.sh

      - name: Check environment variables
        run: ./.github/scripts/check-env-vars.sh
        if: always()
